import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    nursery: 'warn',
  },
  ignorePatterns: [
    '**/build/**',
    '**/dist/**',
    '**/.tmp/**',
    '**/node_modules/**',
    '**/*.d.ts/**',
    '**/.github/**',
    '**/.husky/**',
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    'tools/oxlint/anti-slop/**',
  ],
  jsPlugins: [
    {
      name: 'react-you-might-not-need-an-effect',
      specifier: 'eslint-plugin-react-you-might-not-need-an-effect',
    },
    {
      name: 'anti-slop',
      specifier: './tools/oxlint/anti-slop/index.ts',
    },
  ],
  rules: {
    'oxc/no-accumulating-spread': 'error',
    'anti-slop/no-array-filter-map': 'error',
    'anti-slop/no-reduce-accumulator-copy': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-readable-spacing': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
    'typescript/consistent-type-definitions': ['error', 'type'],
    'typescript/consistent-return': 'off',
    'react-in-jsx-scope': 'off',
    'react/exhaustive-deps': 'warn',
    'typescript/no-floating-promises': 'error',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unnecessary-condition': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/explicit-function-return-type': 'error',
    'no-console': 'error',
    'max-params': ['error', 3],
    'max-lines-per-function': ['warn', { max: 80, skipBlankLines: true, skipComments: true }],
    complexity: ['warn', { max: 10 }],
    'import/no-cycle': ['error', { maxDepth: 3 }],
    eqeqeq: ['error', 'smart'],
    curly: ['error', 'all'],
    'import/export': 'error',
    'import/named': 'error',
    'unicorn/no-null': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/no-array-fill-with-reference-type': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/prefer-export-from': 'warn',
    'unicorn/prefer-single-call': 'warn',
    'unicorn/prefer-spread': 'warn',
    'react/rules-of-hooks': 'error',
    'react/require-render-return': 'error',
    'react/no-multi-comp': 'error',
    'react/no-unstable-nested-components': 'error',
    'react/only-export-components': ['error', { allowConstantExport: true }],
    'react-you-might-not-need-an-effect/no-adjust-state-on-prop-change': 'error',
    'react-you-might-not-need-an-effect/no-chain-state-updates': 'error',
    'react-you-might-not-need-an-effect/no-derived-state': 'error',
    'react-you-might-not-need-an-effect/no-event-handler': 'error',
    'react-you-might-not-need-an-effect/no-external-store-subscription': 'error',
    'react-you-might-not-need-an-effect/no-initialize-state': 'error',
    'react-you-might-not-need-an-effect/no-pass-data-to-parent': 'error',
    'react-you-might-not-need-an-effect/no-pass-live-state-to-parent': 'error',
    'react-you-might-not-need-an-effect/no-reset-all-state-on-prop-change': 'error',
  },
  env: {
    builtin: true,
    es2026: true,
    node: true,
    browser: true,
  },
  options: {
    typeAware: true,
    typeCheck: true,
  },
  plugins: ['typescript', 'import', 'unicorn', 'oxc', 'react', 'jsx-a11y'],
});
