export const constants =  {
   Position_Executive_Director: 'https://forms.gle/rQfU8QUoXnjxWSyf9',
   Position_Hardware_Director: 'https://docs.google.com/forms/d/1-SA8Q4sVc4rw67qjR5RMhOYoXkLfAp5wUIZIU5uQdls/edit',
   Position_Software_Director: 'https://docs.google.com/forms/d/1sUtUaHUN6dUQUXkmGyEFOnK9r5oDe1vORGBZoxMAzrU/edit',
   Position_Ops_Director: 'https://docs.google.com/forms/d/1duYk3ysEKBd9tr_KHlF6f1zsBw_GMeCdJzln85LkMvk/edit',
   Position_Engagement_Director: 'https://docs.google.com/forms/d/1P96KguA1azW6ct8_BjjCi6YtP7CPOvxwj8IS0-PpokA/edit',
   Position_Online_Eng_Coordinator: 'https://forms.gle/t91bnRvBK6NpsmcZ9',
   Position_Photographer: 'https://forms.gle/FVB1WdbPBs22si4T6',
   Position_Videographer : 'https://forms.gle/h2fWBf1zxi9n3uSRA',
   Position_Brand_designer : 'https://forms.gle/h2fWBf1zxi9n3uSRA',
   Position_Office_Manager : 'https://docs.google.com/forms/d/e/1FAIpQLSe-eMae53oKUgu5xNDMDTgYVxWdYpK0I0qKhkCKiNDGWSsS4Q/viewform?usp=sf_link',
   Position_Build_Studio_Support : 'https://docs.google.com/forms/d/e/1FAIpQLSciIXkmLcG2DOl0UONgthXbGfd_elOIjSjqQP4Xh4gg7tSJIg/viewform?usp=sf_link',
   Position_Data_Analyst : 'https://docs.google.com/forms/d/e/1FAIpQLScCWxCo7WVg_wEfPGTc0xfDAfV9QZZCOQgqzcrzqKXs2TVhow/viewform?usp=sf_link',
   Position_Professional_Dev_Specialist : 'https://docs.google.com/forms/d/1_EsBgzKXZJhuQSZ-hsX4dOzwqpCz8sKH32s483L0v_I/edit?usp=sharing',
   Position_Internal_Dev_Specialist  : 'https://forms.gle/kJ1MuAdA8Z1RDiNZ7',
   Position_Hardware_Chief : 'https://forms.gle/ZMgsmWUTkmaJf8e9A',
   Position_Hardware_Project_Lead : 'https://forms.gle/3Ms3S63aBjb8tf9K9',
   Position_Hardware_Tech_Lead : 'https://forms.gle/rekKpX1kq3dDKqtc9',
   Position_Hardware_BSE : 'https://forms.gle/jNrdUSjbfLCGh53v6',
   Position_Hardware_BSD : 'https://forms.gle/voNsviCg7wAqL43u9',
   Position_Software_Tech_Lead : 'https://forms.gle/zRs9VhzDy7GHxgSV9',
   Position_Software_Design_Lead : 'https://forms.gle/MpPBPETURFMZcirf8',
   Position_Software_BSE : 'https://forms.gle/T9wFSbDgQ8nph7zD8',
   Position_Software_BSD : 'https://forms.gle/xyCGoRmKpP6GrVCd9',
   Position_Software_Client : 'https://forms.gle/xyCGoRmKpP6GrVCd9'
}