/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Showcase = {
  _id: string;
  _type: 'showcase';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year: string;
  semester: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type PastProject = {
  _id: string;
  _type: 'pastProject';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  clientName?: string;
  clientTitle?: string;
  semester?: string;
  teamResponsible?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  description?: string;
  quote?: string;
  featured?: boolean;
};

export type GenerateLink = {
  _id: string;
  _type: 'generateLink';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  url: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Value = {
  _id: string;
  _type: 'value';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  value: string;
  color: Color;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  text: string;
  index: number;
};

export type Color = {
  _type: 'color';
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type ApplicationReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'application';
};

export type Team = {
  _id: string;
  _type: 'team';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  team: string;
  cardVariant: 'default' | 'client';
  color: Color;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  team_abbreviation?: string;
  tags: Array<string>;
  teamDescription: string;
  contributorDescription?: string;
  contributorRoles?: Array<
    {
      _key: string;
    } & ApplicationReference
  >;
  leadDescription?: string;
  leadRoles?: Array<
    {
      _key: string;
    } & ApplicationReference
  >;
  chiefDescription?: string;
  chiefRoles?: Array<
    {
      _key: string;
    } & ApplicationReference
  >;
  externalLink?: string;
  zIndex: number;
};

export type Director = {
  _id: string;
  _type: 'director';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  team: string;
  title: string;
  name: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  email: string;
  color: Color;
  zIndex: number;
};

export type Copy = {
  _id: string;
  _type: 'copy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key:
    | 'what-is-generate-landing'
    | 'why-generate-1'
    | 'why-generate-2'
    | 'why-generate-3'
    | 'how-were-structured'
    | 'celebrate-our-wins';
  header: string;
  content: Array<string>;
};

export type Application = {
  _id: string;
  _type: 'application';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  team?: string;
  activeApplication: boolean;
  applicationLink?: string;
};

export type RgbaColor = {
  _type: 'rgbaColor';
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: 'hsvaColor';
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: 'hslaColor';
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Showcase
  | SanityImageCrop
  | SanityImageHotspot
  | PastProject
  | GenerateLink
  | Slug
  | Value
  | Color
  | ApplicationReference
  | Team
  | Director
  | Copy
  | Application
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
